BEGIN;
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE DOMAIN iso_currency AS text CHECK (VALUE ~ '^[A-Z]{3}$');
CREATE DOMAIN minor_units AS bigint CHECK (VALUE >= 0);

CREATE TABLE tenants(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL);
CREATE TABLE accounts(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants, email text NOT NULL, role text NOT NULL, UNIQUE(tenant_id,email));
CREATE TABLE products(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants, name_en text NOT NULL, name_bn text NOT NULL, active boolean NOT NULL DEFAULT true, UNIQUE(tenant_id,id));
CREATE TABLE variants(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants, product_id uuid NOT NULL, sku text NOT NULL, price_minor minor_units NOT NULL, currency iso_currency NOT NULL, UNIQUE(tenant_id,sku), FOREIGN KEY(tenant_id,product_id) REFERENCES products(tenant_id,id));
CREATE TABLE inventory(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants, variant_id uuid NOT NULL, on_hand integer NOT NULL CHECK(on_hand>=0), unit_cost_minor minor_units NOT NULL, UNIQUE(tenant_id,variant_id), FOREIGN KEY(tenant_id,variant_id) REFERENCES variants(tenant_id,id));
CREATE TABLE contacts(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants, phone text, name text, UNIQUE(tenant_id,phone), UNIQUE(tenant_id,id));
CREATE TABLE campaigns(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants, name text NOT NULL, spend_minor minor_units NOT NULL, currency iso_currency NOT NULL, UNIQUE(tenant_id,id));
CREATE TABLE leads(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants, contact_id uuid NOT NULL, status text NOT NULL, campaign_id uuid, FOREIGN KEY(tenant_id,contact_id) REFERENCES contacts(tenant_id,id), FOREIGN KEY(tenant_id,campaign_id) REFERENCES campaigns(tenant_id,id));
CREATE TABLE conversations(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants, contact_id uuid, session_id text NOT NULL, status text NOT NULL, UNIQUE(tenant_id,session_id), UNIQUE(tenant_id,id));
CREATE TABLE messages(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants, conversation_id uuid NOT NULL, role text NOT NULL, body text NOT NULL, created_at timestamptz NOT NULL, FOREIGN KEY(tenant_id,conversation_id) REFERENCES conversations(tenant_id,id));
CREATE TABLE orders(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants, contact_id uuid NOT NULL, status text NOT NULL, payment_method text NOT NULL CHECK(payment_method IN ('cod','prepaid')), total_minor minor_units NOT NULL, currency iso_currency NOT NULL, delivery_address text NOT NULL, created_at timestamptz NOT NULL, idempotency_key text NOT NULL, UNIQUE(tenant_id,idempotency_key), UNIQUE(tenant_id,id));
CREATE TABLE order_items(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants, order_id uuid NOT NULL, variant_id uuid NOT NULL, quantity integer NOT NULL CHECK(quantity>0), unit_price_minor minor_units NOT NULL, currency iso_currency NOT NULL, FOREIGN KEY(tenant_id,order_id) REFERENCES orders(tenant_id,id));
CREATE TABLE touchpoints(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants, contact_id uuid, order_id uuid, campaign_id uuid, occurred_at timestamptz NOT NULL, metadata jsonb NOT NULL);
CREATE TABLE shipments(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants, order_id uuid NOT NULL, status text NOT NULL, delivered_at timestamptz, UNIQUE(tenant_id,order_id,status));
CREATE TABLE payments(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants, order_id uuid NOT NULL, status text NOT NULL, amount_minor minor_units NOT NULL, currency iso_currency NOT NULL, independently_validated boolean NOT NULL DEFAULT false, UNIQUE(tenant_id,order_id,status));
CREATE TABLE outcomes(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants, order_id uuid NOT NULL, stage text NOT NULL CHECK(stage IN ('captured','qualified','converted','verified','disqualified')), updated_at timestamptz NOT NULL, UNIQUE(tenant_id,order_id), UNIQUE(tenant_id,id));
CREATE TABLE outcome_transitions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants, outcome_id uuid NOT NULL, from_stage text, to_stage text NOT NULL, occurred_at timestamptz NOT NULL, audit_evidence jsonb NOT NULL, FOREIGN KEY(tenant_id,outcome_id) REFERENCES outcomes(tenant_id,id));
CREATE TABLE canonical_events(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants, aggregate_id uuid NOT NULL, event_type text NOT NULL, occurred_at timestamptz NOT NULL, data jsonb NOT NULL, idempotency_key text NOT NULL, UNIQUE(tenant_id,idempotency_key), UNIQUE(tenant_id,id));
CREATE TABLE contract_versions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants, version integer NOT NULL, pricing_model text NOT NULL CHECK(pricing_model='fixed'), fixed_fee_minor minor_units NOT NULL, currency iso_currency NOT NULL, effective_at timestamptz NOT NULL, UNIQUE(tenant_id,version));
CREATE TABLE billable_results(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants, outcome_id uuid NOT NULL, contract_version_id uuid NOT NULL REFERENCES contract_versions, amount_minor minor_units NOT NULL, currency iso_currency NOT NULL, created_at timestamptz NOT NULL, UNIQUE(tenant_id,outcome_id), UNIQUE(tenant_id,id));
CREATE TABLE ledger_entries(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants, entry_type text NOT NULL CHECK(entry_type='performance_fee_accrual'), amount_minor minor_units NOT NULL, currency iso_currency NOT NULL, billable_result_id uuid NOT NULL, idempotency_key text NOT NULL, created_at timestamptz NOT NULL, evidence jsonb NOT NULL, UNIQUE(tenant_id,idempotency_key), UNIQUE(tenant_id,billable_result_id,entry_type), FOREIGN KEY(tenant_id,billable_result_id) REFERENCES billable_results(tenant_id,id));
CREATE TABLE outbox_messages(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants, event_id uuid NOT NULL, payload jsonb NOT NULL, created_at timestamptz NOT NULL, processed_at timestamptz, UNIQUE(tenant_id,event_id), FOREIGN KEY(tenant_id,event_id) REFERENCES canonical_events(tenant_id,id));
CREATE TABLE faq_policies(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants, kind text NOT NULL, title_en text NOT NULL, title_bn text NOT NULL, body_en text NOT NULL, body_bn text NOT NULL);
CREATE TABLE otp_challenges(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants, phone text NOT NULL, code_hash text NOT NULL, expires_at timestamptz NOT NULL, consumed_at timestamptz);

-- Tenant isolation is defense in depth; the API must SET app.tenant_id per transaction.
DO $$ DECLARE t text; BEGIN FOREACH t IN ARRAY ARRAY['accounts','products','variants','inventory','contacts','campaigns','leads','conversations','messages','orders','order_items','touchpoints','shipments','payments','outcomes','outcome_transitions','canonical_events','contract_versions','billable_results','ledger_entries','outbox_messages','faq_policies','otp_challenges'] LOOP EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY',t); EXECUTE format('CREATE POLICY tenant_scope ON %I USING (tenant_id = current_setting(''app.tenant_id'')::uuid) WITH CHECK (tenant_id = current_setting(''app.tenant_id'')::uuid)',t); END LOOP; END $$;
COMMIT;
