PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS tenants(id TEXT PRIMARY KEY,name TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS products(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,name_en TEXT NOT NULL,name_bn TEXT NOT NULL,active INTEGER NOT NULL,UNIQUE(tenant_id,id));
CREATE TABLE IF NOT EXISTS variants(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,product_id TEXT NOT NULL,sku TEXT NOT NULL,price_minor INTEGER NOT NULL CHECK(price_minor>=0),currency TEXT NOT NULL CHECK(length(currency)=3),UNIQUE(tenant_id,sku));
CREATE TABLE IF NOT EXISTS inventory(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,variant_id TEXT NOT NULL,on_hand INTEGER NOT NULL CHECK(on_hand>=0),unit_cost_minor INTEGER NOT NULL CHECK(unit_cost_minor>=0),UNIQUE(tenant_id,variant_id));
CREATE TABLE IF NOT EXISTS contacts(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,phone TEXT,name TEXT,UNIQUE(tenant_id,phone));
CREATE TABLE IF NOT EXISTS leads(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,contact_id TEXT NOT NULL,status TEXT NOT NULL,campaign_id TEXT);
CREATE TABLE IF NOT EXISTS conversations(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,contact_id TEXT,session_id TEXT NOT NULL,status TEXT NOT NULL,UNIQUE(tenant_id,session_id));
CREATE TABLE IF NOT EXISTS messages(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,conversation_id TEXT NOT NULL,role TEXT NOT NULL,body TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS campaigns(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,name TEXT NOT NULL,spend_minor INTEGER NOT NULL,currency TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS touchpoints(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,contact_id TEXT,order_id TEXT,campaign_id TEXT,occurred_at TEXT NOT NULL,metadata TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS orders(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,contact_id TEXT NOT NULL,status TEXT NOT NULL,payment_method TEXT NOT NULL,total_minor INTEGER NOT NULL,currency TEXT NOT NULL,delivery_address TEXT NOT NULL,created_at TEXT NOT NULL,idempotency_key TEXT NOT NULL,UNIQUE(tenant_id,idempotency_key));
CREATE TABLE IF NOT EXISTS order_items(id TEXT PRIMARY KEY,order_id TEXT NOT NULL,tenant_id TEXT NOT NULL,variant_id TEXT NOT NULL,quantity INTEGER NOT NULL,unit_price_minor INTEGER NOT NULL,currency TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS shipments(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,order_id TEXT NOT NULL,status TEXT NOT NULL,delivered_at TEXT,UNIQUE(tenant_id,order_id,status));
CREATE TABLE IF NOT EXISTS payments(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,order_id TEXT NOT NULL,status TEXT NOT NULL,amount_minor INTEGER NOT NULL,currency TEXT NOT NULL,independently_validated INTEGER NOT NULL,UNIQUE(tenant_id,order_id,status));
CREATE TABLE IF NOT EXISTS outcomes(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,order_id TEXT NOT NULL,stage TEXT NOT NULL,updated_at TEXT NOT NULL,UNIQUE(tenant_id,order_id));
CREATE TABLE IF NOT EXISTS outcome_transitions(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,outcome_id TEXT NOT NULL,from_stage TEXT,to_stage TEXT NOT NULL,occurred_at TEXT NOT NULL,audit_evidence TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS canonical_events(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,aggregate_id TEXT NOT NULL,event_type TEXT NOT NULL,occurred_at TEXT NOT NULL,data TEXT NOT NULL,idempotency_key TEXT NOT NULL,UNIQUE(tenant_id,idempotency_key));
CREATE TABLE IF NOT EXISTS contract_versions(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,version INTEGER NOT NULL,pricing_model TEXT NOT NULL,fixed_fee_minor INTEGER NOT NULL,currency TEXT NOT NULL,effective_at TEXT NOT NULL DEFAULT '1970-01-01T00:00:00+00:00',UNIQUE(tenant_id,version));
CREATE TABLE IF NOT EXISTS billable_results(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,outcome_id TEXT NOT NULL,contract_version_id TEXT NOT NULL,amount_minor INTEGER NOT NULL,currency TEXT NOT NULL,created_at TEXT NOT NULL,UNIQUE(tenant_id,outcome_id));
CREATE TABLE IF NOT EXISTS ledger_entries(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,entry_type TEXT NOT NULL,amount_minor INTEGER NOT NULL,currency TEXT NOT NULL,billable_result_id TEXT NOT NULL,idempotency_key TEXT NOT NULL,created_at TEXT NOT NULL,evidence TEXT NOT NULL,UNIQUE(tenant_id,idempotency_key),UNIQUE(tenant_id,billable_result_id,entry_type));
CREATE TABLE IF NOT EXISTS outbox_messages(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,event_id TEXT NOT NULL,payload TEXT NOT NULL,created_at TEXT NOT NULL,processed_at TEXT,UNIQUE(tenant_id,event_id));
CREATE TABLE IF NOT EXISTS otp_challenges(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,phone TEXT NOT NULL,code_hash TEXT NOT NULL,expires_at TEXT NOT NULL,consumed_at TEXT);
CREATE TABLE IF NOT EXISTS faq_policies(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,kind TEXT NOT NULL,title_en TEXT NOT NULL,title_bn TEXT NOT NULL,body_en TEXT NOT NULL,body_bn TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS accounts(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,email TEXT NOT NULL,role TEXT NOT NULL,UNIQUE(tenant_id,email));
